#!/bin/bash
#   Copyright (C) 2021 University of Oxford
#   SHCOPYRIGHT
#set -e
#set -x

######

if [ $# -lt 3 ] ; then
  echo "Usage: `basename $0` --basemodality=<basemodality_name> --outname=<output_basename> --FLAIR=<FLAIR_image_name> --T1=<T1_image_name> --T1ce=<T1ce_image_name> --T2=<T2_image_name> [--keepintermediate] [-savelog]"
  echo " "
  echo "The script applies the preprocessing pipeline on FLAIR, T1, T1ce and T2 to be used in FSL truenet_tumseg with a specified output basename"
  echo "Base_modality_name and output_basename are mandatory inputs"
  echo "Remaining inputs are optional, image corresponding to Base_modality_name must be provided."
  echo "The script applies the preprocessing pipeline on FLAIR, T1 and WM mask to be used in FSL truenet with a specified output basename"
  echo "basemodality_name		= 	name of the modality that the rest will be registered to (preferable ~1mm iso); 
  									valid options: flair, t1, t1ce, t2"
  echo "output_basename 		= 	absolute/relative path for the processed FLAIR and T1 images; output_basename_FLAIR.nii.gz, output_basename_T1.nii.gz etc. will be saved"
  echo "FLAIR_image_name 		= 	absolute/relative path of the input unprocessed FLAIR image with the nifti file"
  echo "T1_image_name 			= 	absolute/relative path of the input unprocessed T1 image with the nifti file"
  echo "T1ce_image_name = 	name of the input unprocessed T1-contrast enhanced image"
  echo "T2_image_name = 	name of the input unprocessed T2 image"
  echo "specify --keepintermediate if you want to save intermediate results"
  echo "specify --savelog for saving the comments (steps in preprocessing) in a log file"
  echo " "
  echo "For example, if you have flair, t1 and t2 and want to register everything to t1, and want to keep intermediate files, use the following command"
  echo "prepare_tumseg_data --basemodality=t1 --outname=path/to/outputbasename --FLAIR=path/to/input_flair.nii.gz --T1=path/to/input_t1.nii.gz --T2=path/to/input_t2.nii.gz --keepintermediate"  
  exit 0
fi

get_opt1() {
    arg=`echo $1 | sed 's/=.*//'`
    echo $arg
}

get_arg1() {
    if [ X`echo $1 | grep '='` = X ] ; then 
	echo "Option $1 requires an argument" 1>&2
	exit 1
    else 
	arg=`echo $1 | sed 's/.*=//'`
	if [ X$arg = X ] ; then
	    echo "Option $1 requires an argument" 1>&2
	    exit 1
	fi
	echo $arg
    fi
}

get_arg2() {
    if [ X$2 = X ] ; then
	echo "Option $1 requires an argument" 1>&2
	exit 1
    fi
    echo $2
}

# default options
argbase=
argout=
flairfile=
t1file=
t1cefile=
t2file=
verbose=no
keepint=no

if [ $# -eq 0 ] ; then usage; exit 0; fi
if [ $# -lt 4 ] ; then usage; exit 1; fi
niter=0;
while [ $# -ge 1 ] ; do
    niter=`echo $niter + 1 | bc`;
    iarg=`get_opt1 $1`;
    case "$iarg"
	in
	--savelog)
	    verbose=yes; 
	    shift;;
	--keepintermediate)
	    keepint=yes;
	    shift;;
	--FLAIR)
	    flairfile=`get_arg1 $1`;
	    shift;;
	--T1)
	    t1file=`get_arg1 $1`;
	    shift;;
	--T1ce)
	    t1cefile=`get_arg1 $1`;
	    shift;;
	--T2)
	    t2file=`get_arg1 $1`;
	    shift;;
	--outname)
	    argout=`get_arg1 $1`;
	    shift;;
	--basemodality)
	    argbase=`get_arg1 $1`;
	    shift;;
	*)
	    usage;
	    echo "Unrecognised option $1" 1>&2
	    exit 1
    esac
done

outname=`basename ${argout}`
outdir=`dirname ${argout}`
pushd $outdir > /dev/null
outdir=`pwd`
popd > /dev/null

if [ ${verbose} = yes ] ; then
logfile=`echo ${outdir}/${outname}_logfile.txt`
echo "Creating command log for prepare_truenet_data" > ${logfile}
echo "`date`: Checking if FSL is setup" >> ${logfile}
fi

if [ X${FSLDIR} = X ] ; then
    echo "ERROR: Cannot find FSL"
    echo "       Please setup the environment variable FSLDIR and try again"
    exit 1
fi

if [ X${flairfile} = X ] ; then
flairflag=0
else
if [ ${verbose} = yes ] ; then
echo "`date`: Reading the input FLAIR file" >> ${logfile}
fi
flairflag=1
flairimg=`basename ${flairfile} .nii.gz`
flairdir=`dirname ${flairfile} `
pushd $flairdir > /dev/null
flairdir=`pwd`
popd > /dev/null
fi

if [ X${t1file} = X ] ; then
t1flag=0
else
if [ ${verbose} = yes ] ; then
echo "`date`: Reading the input T1 file" >> ${logfile}
fi
t1flag=1
t1img=`basename ${t1file} .nii.gz`
t1dir=`dirname ${t1file} `
pushd $t1dir > /dev/null
t1dir=`pwd`
popd > /dev/null
fi

if [ X${t1cefile} = X ] ; then
t1ceflag=0
else
if [ ${verbose} = yes ] ; then
echo "`date`: Reading the input T1ce file" >> ${logfile}
fi
t1ceflag=1
t1ceimg=`basename ${t1cefile} .nii.gz`
t1cedir=`dirname ${t1cefile} `
pushd $t1cedir > /dev/null
t1cedir=`pwd`
popd > /dev/null
fi

if [ X${t2file} = X ] ; then
t2flag=0
else
if [ ${verbose} = yes ] ; then
echo "`date`: Reading the input T2 file" >> ${logfile}
fi
t2flag=1
t2img=`basename ${t2file} .nii.gz`
t2dir=`dirname ${t2file} `
pushd $t2dir > /dev/null
t2dir=`pwd`
popd > /dev/null
fi

if [ ${verbose} = yes ] ; then
echo "`date`: Checking base modality and mandatory files" >> ${logfile}
fi
if [[ ${argbase} == 'flair' || ${argbase} == 't1' || ${argbase} == 't1ce' || ${argbase} == 't2' ]]; then
base_type=`echo ${argbase}`
else
error_exit "Invalid option provided for Base_modality_type! Cannot proceed..."
fi

if [[ $base_type == 'flair' ]]; then
	if [ $flairflag -eq 0 ] ; then
	error_exit "FLAIR_image_name cannot be None if Base_modality_type is flair! Cannot proceed..."
	else
	inbasename=$flairfile
	fi
elif [[ $base_type == 't1' ]]; then
	if [ $t1flag -eq 0 ] ; then
	error_exit "T1_image_name cannot be None if Base_modality_type is t1! Cannot proceed..."
	else
	inbasename=$t1file
	fi
elif [[ $base_type == 't1ce' ]]; then
	if [ $t1ceflag -eq 0 ] ; then
	error_exit "T1ce_image_name cannot be None if Base_modality_type is t1ce! Cannot proceed..."
	else
	inbasename=$t1cefile
	fi
elif [[ $base_type == 't2' ]]; then
	if [ $t2flag -eq 0 ] ; then
	error_exit "T2_image_name cannot be None if Base_modality_type is t2! Cannot proceed..."
	else
	inbasename=$t2file
	fi
fi

# SPECIFY ORIGINAL DIRECTORY
origdir=`pwd`

# CREATE TEMPORARY DIRECTORY
if [ ${verbose} = yes ] ; then
echo "`date`: Creating a temporary directory" >> ${logfile}
fi
logID=`echo $(date | awk '{print $1 $2 $3}' |  sed 's/://g')`
TMPVISDIR=`mktemp -d ${outdir}/tumseg_${logID}_${flairimg}_${t1img}_XXXXXX`

# REORIENTING THE AVAILABLE IMAGES TO STD SPACE AND BRAIN EXTRACTION
if [ $flairflag -eq 1 ] ; then
if [ ${verbose} = yes ] ; then
echo "`date`: Reorienting input FLAIR image" >> ${logfile}
fi
$FSLDIR/bin/fslreorient2std ${flairfile}.nii.gz ${TMPVISDIR}/FLAIR_reorient.nii.gz
if [ ${verbose} = yes ] ; then
echo "`date`: Extracting brain ROI for FLAIR image" >> ${logfile}
fi
$FSLDIR/bin/robustfov -i ${TMPVISDIR}/FLAIR_reorient.nii.gz -r ${TMPVISDIR}/FLAIR_reorient_robustfov.nii.gz
if [ ${verbose} = yes ] ; then
echo "`date`: Extracting brain for FLAIR image and getting the brain mask" >> ${logfile}
fi
$FSLDIR/bin/bet ${TMPVISDIR}/FLAIR_reorient_robustfov.nii.gz ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz -S
$FSLDIR/bin/fslmaths ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz -bin -fillh ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz
$FSLDIR/bin/fslmaths ${TMPVISDIR}/FLAIR_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz
fi
if [ $t1flag -eq 1 ] ; then
if [ ${verbose} = yes ] ; then
echo "`date`: Reorienting input T1 image" >> ${logfile}
fi
$FSLDIR/bin/fslreorient2std ${t1file}.nii.gz ${TMPVISDIR}/T1_reorient.nii.gz
if [ ${verbose} = yes ] ; then
echo "`date`: Extracting brain ROI for T1 image" >> ${logfile}
fi
$FSLDIR/bin/robustfov -i ${TMPVISDIR}/T1_reorient.nii.gz -r ${TMPVISDIR}/T1_reorient_robustfov.nii.gz
if [ ${verbose} = yes ] ; then
echo "`date`: Extracting brain for T1 image" >> ${logfile}
fi
$FSLDIR/bin/bet ${TMPVISDIR}/T1_reorient_robustfov.nii.gz ${TMPVISDIR}/T1_reorient_robustfov_brain.nii.gz -S
fi
if [ $t1ceflag -eq 1 ] ; then
if [ ${verbose} = yes ] ; then
echo "`date`: Reorienting input T1ce image" >> ${logfile}
fi
$FSLDIR/bin/fslreorient2std ${t1cefile}.nii.gz ${TMPVISDIR}/T1ce_reorient.nii.gz
if [ ${verbose} = yes ] ; then
echo "`date`: Extracting brain ROI for T1ce image" >> ${logfile}
fi
$FSLDIR/bin/robustfov -i ${TMPVISDIR}/T1ce_reorient.nii.gz -r ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz
if [ ${verbose} = yes ] ; then
echo "`date`: Extracting brain for T1ce image and getting the brain mask" >> ${logfile}
fi
$FSLDIR/bin/bet ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz ${TMPVISDIR}/T1ce_reorient_robustfov_brain.nii.gz -S
$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_reorient_robustfov_brain.nii.gz -bin -fillh ${TMPVISDIR}/T1ce_robustfov_brain_mask.nii.gz
fi
if [ $t2flag -eq 1 ] ; then
if [ ${verbose} = yes ] ; then
echo "`date`: Reorienting input T2 image" >> ${logfile}
fi
$FSLDIR/bin/fslreorient2std ${t2file}.nii.gz ${TMPVISDIR}/T2_reorient.nii.gz
if [ ${verbose} = yes ] ; then
echo "`date`: Extracting brain ROI for T2 image" >> ${logfile}
fi
$FSLDIR/bin/robustfov -i ${TMPVISDIR}/T2_reorient.nii.gz -r ${TMPVISDIR}/T2_reorient_robustfov.nii.gz
if [ ${verbose} = yes ] ; then
echo "`date`: Extracting brain for T2 image" >> ${logfile}
fi
$FSLDIR/bin/bet ${TMPVISDIR}/T2_reorient_robustfov.nii.gz ${TMPVISDIR}/T2_reorient_robustfov_brain.nii.gz -S
fi

# CONSIDERING FLAIR AS BASE MODALITY; PROCESSING AVAILABLE MODALITIES WRT FLAIR
if [[ $base_type == 'flair' ]]; then
	if [ ${verbose} = yes ] ; then
	echo "Considering FLAIR as base modality..." >> ${logfile}
	fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz ${outdir}/${outname}_FLAIR.nii.gz
	if [ $t1flag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T1 to FLAIR and applying FLAIR brain mask" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T1_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/FLAIR_reorient_robustfov.nii.gz -out ${TMPVISDIR}/T1_robustfov_2FLAIR.nii.gz -omat ${TMPVISDIR}/T1_robustfov_2FLAIR.mat
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2FLAIR.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_2FLAIR_brain.nii.gz
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T1_robustfov_2FLAIR_brain.nii.gz ${outdir}/${outname}_T1.nii.gz
	fi
	if [ $t1ceflag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T1ce to FLAIR and applying FLAIR brain mask" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/FLAIR_reorient_robustfov.nii.gz -out ${TMPVISDIR}/T1ce_robustfov_2FLAIR.nii.gz -omat ${TMPVISDIR}/T1ce_robustfov_2FLAIR.mat
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2FLAIR.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2FLAIR_brain.nii.gz
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T1ce_robustfov_2FLAIR_brain.nii.gz ${outdir}/${outname}_T1ce.nii.gz
	fi
	if [ $t2flag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T2 to FLAIR and applying FLAIR brain mask" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T2_reorient_robustfov_brain.nii.gz -ref ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz -out ${TMPVISDIR}/T2_robustfov_2FLAIR.nii.gz -omat ${TMPVISDIR}/T2_robustfov_2FLAIR.mat
	$FSLDIR/bin/flirt -in ${TMPVISDIR}/T2_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz -out ${TMPVISDIR}/T2_robustfov_2FLAIR.nii.gz -init ${TMPVISDIR}/T2_robustfov_2FLAIR.mat -applyxfm
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_robustfov_2FLAIR.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T2_robustfov_2FLAIR_brain.nii.gz
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T2_robustfov_2FLAIR_brain.nii.gz ${outdir}/${outname}_T2.nii.gz
	fi
	if [ ${keepint} = yes ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Saving intermediate files ..." >> ${logfile}
	fi
	# SAVING INTERMEDIATE FILES
	######################################################################################
	mv ${TMPVISDIR} ${outdir}/${outname}_temp/
	fi
# CONSIDERING T1 AS BASE MODALITY; PROCESSING AVAILABLE MODALITIES WRT T1 (IF FLAIR, TAKE BRAIN_MASK FROM FLAIR)
elif [[ $base_type == 't1' ]]; then
	if [ ${verbose} = yes ] ; then
	echo "Considering T1 as base modality..." >> ${logfile}
	fi
	if [ $flairflag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering FLAIR to T1 and brain extraction" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz -ref ${TMPVISDIR}/T1_reorient_robustfov_brain.nii.gz -out ${TMPVISDIR}/FLAIR_robustfov_2T1.nii.gz -omat ${TMPVISDIR}/FLAIR_robustfov_2T1.mat
	$FSLDIR/bin/flirt -in ${TMPVISDIR}/FLAIR_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T1_reorient_robustfov_brain.nii.gz -out ${TMPVISDIR}/FLAIR_robustfov_2T1.nii.gz -init ${TMPVISDIR}/FLAIR_robustfov_2T1.mat -applyxfm
	$FSLDIR/bin/bet ${TMPVISDIR}/FLAIR_robustfov_2T1.nii.gz ${TMPVISDIR}/FLAIR_robustfov_2T1_brain.nii.gz -S
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/FLAIR_robustfov_2T1_brain.nii.gz -bin -fillh ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/FLAIR_robustfov_2T1.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/FLAIR_robustfov_2T1_brain.nii.gz
	${FSLDIR}/bin/imcp ${TMPVISDIR}/FLAIR_robustfov_2T1_brain.nii.gz ${outdir}/${outname}_FLAIR.nii.gz
	fi
	if [ $t2flag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T2 to T1" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T2_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T1_reorient_robustfov.nii.gz -out ${TMPVISDIR}/T2_robustfov_2T1.nii.gz -omat ${TMPVISDIR}/T2_robustfov_2T1.mat
		if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
		if [ ${verbose} = yes ] ; then
		echo "`date`: FLAIR brain mask found, applying on T2" >> ${logfile}
		fi
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_robustfov_2T1.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T2_robustfov_2T1_brain.nii.gz
		else
		if [ ${verbose} = yes ] ; then
		echo "`date`: FLAIR brain mask not found, exracting brain on T2" >> ${logfile}
		fi
		$FSLDIR/bin/bet ${TMPVISDIR}/T2_robustfov_2T1.nii.gz ${TMPVISDIR}/T2_robustfov_2T1_brain.nii.gz -S
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_robustfov_2T1_brain.nii.gz -bin -fillh ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_robustfov_2T1.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T2_robustfov_2T1_brain.nii.gz
		fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T2_robustfov_2T1_brain.nii.gz ${outdir}/${outname}_T2.nii.gz
	fi
	if [ ${verbose} = yes ] ; then
	echo "`date`: Applying brain mask on T1" >> ${logfile}
	fi
	if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_brain.nii.gz
	elif [ -f "${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz" ]; then
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_brain.nii.gz
	else
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_brain.nii.gz -bin -fillh ${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz	
	fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T1_robustfov_brain.nii.gz ${outdir}/${outname}_T1.nii.gz
	if [ $t1ceflag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T1ce to T1" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T1_reorient_robustfov.nii.gz -out ${TMPVISDIR}/T1ce_robustfov_2T1.nii.gz -omat ${TMPVISDIR}/T1ce_robustfov_2T1.mat
	if [ ${verbose} = yes ] ; then
	echo "`date`: Applying brain mask on T1ce" >> ${logfile}
	fi
		if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T1.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T1_brain.nii.gz
		elif [ -f "${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T1.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T1_brain.nii.gz
		elif [ -f "${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T1.nii.gz -mul ${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T1_brain.nii.gz
		else
		$FSLDIR/bin/bet ${TMPVISDIR}/T1ce_robustfov_2T1.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T1_brain.nii.gz -S
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T1_brain.nii.gz -bin -fillh ${TMPVISDIR}/T1ce_robustfov_brain_mask.nii.gz
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T1.nii.gz -mul ${TMPVISDIR}/T1ce_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T1_brain.nii.gz
		fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T1ce_robustfov_2T1_brain.nii.gz ${outdir}/${outname}_T1ce.nii.gz
	fi	
	if [ ${keepint} = yes ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Saving intermediate files ..." >> ${logfile}
	fi
	# SAVING INTERMEDIATE FILES
	######################################################################################
	mv ${TMPVISDIR} ${outdir}/${outname}_temp/
	fi
# CONSIDERING T1CE AS BASE MODALITY; PROCESSING AVAILABLE MODALITIES WRT T1CE (IF FLAIR, TAKE BRAIN_MASK FROM FLAIR)
elif [[ $base_type == 't1ce' ]]; then
	if [ ${verbose} = yes ] ; then
	echo "Considering T1ce as base modality..." >> ${logfile}
	fi
	if [ $flairflag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering FLAIR to T1ce and brain extraction" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz -ref ${TMPVISDIR}/T1ce_reorient_robustfov_brain.nii.gz -out ${TMPVISDIR}/FLAIR_robustfov_2T1ce.nii.gz -omat ${TMPVISDIR}/FLAIR_robustfov_2T1ce.mat
	$FSLDIR/bin/flirt -in ${TMPVISDIR}/FLAIR_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T1ce_reorient_robustfov_brain.nii.gz -out ${TMPVISDIR}/FLAIR_robustfov_2T1ce.nii.gz -init ${TMPVISDIR}/FLAIR_robustfov_2T1ce.mat -applyxfm
	$FSLDIR/bin/bet ${TMPVISDIR}/FLAIR_robustfov_2T1ce.nii.gz ${TMPVISDIR}/FLAIR_robustfov_2T1ce_brain.nii.gz
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/FLAIR_robustfov_2T1ce_brain.nii.gz -bin -fillh ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/FLAIR_robustfov_2T1ce.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/FLAIR_robustfov_2T1ce_brain.nii.gz
	${FSLDIR}/bin/imcp ${TMPVISDIR}/FLAIR_robustfov_2T1ce_brain.nii.gz ${outdir}/${outname}_FLAIR.nii.gz
	fi
	if [ $t2flag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T2 to T1ce" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T2_reorient_robustfov.nii.gz -omat ${TMPVISDIR}/T1ce_robustfov_2T2.mat
	$FSLDIR/bin/convert_xfm -omat ${TMPVISDIR}/T2_robustfov_2T1ce.mat -inverse ${TMPVISDIR}/T1ce_robustfov_2T2.mat
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T2_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -applyxfm -init ${TMPVISDIR}/T2_robustfov_2T1ce.mat -out ${TMPVISDIR}/T2_robustfov_2T1ce.nii.gz
	if [ ${verbose} = yes ] ; then
	echo "`date`: Applying brain mask on T2" >> ${logfile}
	fi
		if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_robustfov_2T1ce.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T2_robustfov_2T1ce_brain.nii.gz
		else
		$FSLDIR/bin/bet ${TMPVISDIR}/T2_robustfov_2T1ce.nii.gz ${TMPVISDIR}/T2_robustfov_2T1ce_brain.nii.gz -S
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_robustfov_2T1ce_brain.nii.gz -bin -fillh ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_robustfov_2T1ce.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T2_robustfov_2T1ce_brain.nii.gz
		fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T2_robustfov_2T1ce_brain.nii.gz ${outdir}/${outname}_T2.nii.gz
	fi
	if [ $t1flag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T1 to T1ce" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T1_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -out ${TMPVISDIR}/T1_robustfov_2T1ce.nii.gz -omat ${TMPVISDIR}/T1_robustfov_2T1ce.mat
	if [ ${verbose} = yes ] ; then
	echo "`date`: Applying brain mask on T1" >> ${logfile}
	fi
		if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2T1ce.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_2T1ce_brain.nii.gz
		elif [ -f "${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2T1ce.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_2T1ce_brain.nii.gz
		else
		$FSLDIR/bin/bet ${TMPVISDIR}/T1_robustfov_2T1ce.nii.gz ${TMPVISDIR}/T1_robustfov_2T1ce_brain.nii.gz -S
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2T1ce_brain.nii.gz -bin -fillh ${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2T1ce.nii.gz -mul ${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_2T1ce_brain.nii.gz
		fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T1_robustfov_2T1ce_brain.nii.gz ${outdir}/${outname}_T1.nii.gz
	fi	
	if [ ${verbose} = yes ] ; then
	echo "`date`: Applying brain mask on T1ce" >> ${logfile}
	fi
	if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_brain.nii.gz
	elif [ -f "${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz" ]; then
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_brain.nii.gz
	elif [ -f "${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz" ]; then
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_brain.nii.gz
	else
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/T1ce_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_brain.nii.gz
	fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T1ce_robustfov_brain.nii.gz ${outdir}/${outname}_T1ce.nii.gz
	if [ ${keepint} = yes ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Saving intermediate files ..." >> ${logfile}
	fi
	# SAVING INTERMEDIATE FILES
	######################################################################################
	mv ${TMPVISDIR} ${outdir}/${outname}_temp/
	fi
elif [[ $base_type == 't2' ]]; then
	if [ ${verbose} = yes ] ; then
	echo "Considering T2 as base modality..." >> ${logfile}
	fi
	if [ $flairflag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering FLAIR to T2 and brain extraction" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/FLAIR_reorient_robustfov_brain.nii.gz -ref ${TMPVISDIR}/T2_reorient_robustfov_brain.nii.gz -out ${TMPVISDIR}/FLAIR_robustfov_2T2.nii.gz -omat ${TMPVISDIR}/FLAIR_robustfov_2T2.mat
	$FSLDIR/bin/flirt -in ${TMPVISDIR}/FLAIR_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T2_reorient_robustfov_brain.nii.gz -out ${TMPVISDIR}/FLAIR_robustfov_2T2.nii.gz -init ${TMPVISDIR}/FLAIR_robustfov_2T2.mat -applyxfm
	$FSLDIR/bin/bet ${TMPVISDIR}/FLAIR_robustfov_2T2.nii.gz ${TMPVISDIR}/FLAIR_robustfov_2T2_brain.nii.gz -S
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/FLAIR_robustfov_2T2_brain.nii.gz -bin -fillh ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/FLAIR_robustfov_2T2.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/FLAIR_robustfov_2T2_brain.nii.gz
	${FSLDIR}/bin/imcp ${TMPVISDIR}/FLAIR_robustfov_2T2_brain.nii.gz ${outdir}/${outname}_FLAIR.nii.gz
	fi
	if [ ${verbose} = yes ] ; then
	echo "`date`: Applying brain mask on T2" >> ${logfile}
	fi
	if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T2_robustfov_brain.nii.gz
	else
	$FSLDIR/bin/bet ${TMPVISDIR}/T2_reorient_robustfov.nii.gz ${TMPVISDIR}/T2_robustfov_brain.nii.gz -S
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_robustfov_brain.nii.gz -bin -fillh ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz
	$FSLDIR/bin/fslmaths ${TMPVISDIR}/T2_reorient_robustfov.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T2_robustfov_brain.nii.gz
	fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T2_robustfov_brain.nii.gz ${outdir}/${outname}_T2.nii.gz
	if [ $t1flag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T1 to T2" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T1_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T2_reorient_robustfov.nii.gz -out ${TMPVISDIR}/T1_robustfov_2T2.nii.gz -omat ${TMPVISDIR}/T1_robustfov_2T2.mat
	if [ ${verbose} = yes ] ; then
	echo "`date`: Applying brain mask on T1" >> ${logfile}
	fi
		if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2T2.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_2T2_brain.nii.gz
		elif [ -f "${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2T2.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_2T2_brain.nii.gz
		else
		$FSLDIR/bin/bet ${TMPVISDIR}/T1_robustfov_2T2.nii.gz ${TMPVISDIR}/T1_robustfov_2T2_brain.nii.gz -S
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2T2_brain.nii.gz -bin -fillh ${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1_robustfov_2T2.nii.gz -mul ${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1_robustfov_2T2_brain.nii.gz
		fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T1_robustfov_2T2_brain.nii.gz ${outdir}/${outname}_T1.nii.gz
	fi
	if [ $t1ceflag -eq 1 ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Registering T1ce to T2" >> ${logfile}
	fi
	$FSLDIR/bin/flirt -dof 6 -in ${TMPVISDIR}/T1ce_reorient_robustfov.nii.gz -ref ${TMPVISDIR}/T2_reorient_robustfov.nii.gz -out ${TMPVISDIR}/T1ce_robustfov_2T2.nii.gz -omat ${TMPVISDIR}/T1ce_robustfov_2T2.mat
	if [ ${verbose} = yes ] ; then
	echo "`date`: Applying brain mask on T1ce" >> ${logfile}
	fi
		if [ -f "${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T2.nii.gz -mul ${TMPVISDIR}/FLAIR_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T2_brain.nii.gz
		elif [ -f "${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T2.nii.gz -mul ${TMPVISDIR}/T2_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T2_brain.nii.gz
		elif [ -f "${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz" ]; then
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T2.nii.gz -mul ${TMPVISDIR}/T1_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T2_brain.nii.gz
		else
		$FSLDIR/bin/bet ${TMPVISDIR}/T1ce_robustfov_2T2.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T2_brain.nii.gz -S
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T2_brain.nii.gz -bin -fillh ${TMPVISDIR}/T1ce_robustfov_brain_mask.nii.gz
		$FSLDIR/bin/fslmaths ${TMPVISDIR}/T1ce_robustfov_2T2.nii.gz -mul ${TMPVISDIR}/T1ce_robustfov_brain_mask.nii.gz ${TMPVISDIR}/T1ce_robustfov_2T2_brain.nii.gz	
		fi
	${FSLDIR}/bin/imcp ${TMPVISDIR}/T1ce_robustfov_2T2_brain.nii.gz ${outdir}/${outname}_T1ce.nii.gz
	fi	
	if [ ${keepint} = yes ] ; then
	if [ ${verbose} = yes ] ; then
	echo "`date`: Saving intermediate files ..." >> ${logfile}
	fi
	# SAVING INTERMEDIATE FILES
	######################################################################################
	mv ${TMPVISDIR} ${outdir}/${outname}_temp/
	fi
fi

# REMOVES TEMPORARY DIRECTORY 
if [ ${keepint} != yes ] ; then
if [ ${verbose} = yes ] ; then
echo "`date`: Intermediate files not requested. Deleting the temporary directory" >> ${logfile}
fi
rm -r ${TMPVISDIR}
fi

if [ ${verbose} = yes ] ; then
echo "Done!" >> ${logfile}
fi

exit 0














